version: "3.5"
services:
  php-fpm:
    image: quay.io/warden/php-fpm:7.3-magento2
    volumes:
      - ${GITHUB_WORKSPACE}:/var/www/html
    networks:
      default:

  php-blackfire:
    image: quay.io/warden/php-fpm:7.3-magento2-blackfire
    volumes:
      - ${GITHUB_WORKSPACE}:/var/www/html
    networks:
      default:

  blackfire-agent:
    image: blackfire/blackfire:latest
    environment:
      - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID}
      - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN}
      - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID}
      - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN}
    networks:
      default:

  mysql:
    image: quay.io/warden/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123123q
      - MYSQL_DATABASE=magento_performance_tests
    ports:
      - 3306
    healthcheck:
      test: mysqladmin ping
      interval: 10s
      retries: 3
    networks:
      default:

  rabbitmq:
    image: quay.io/warden/rabbitmq:3.7
    ports:
      - 5672
    healthcheck:
      test: rabbitmqctl node_health_check
      interval: 10s
      retries: 3
    networks:
      default:

  nginx:
    networks:
      default:
        aliases:
          - magento2.test
    user: root
    volumes:
      - ${GITHUB_WORKSPACE}:/var/www/html
    image: quay.io/warden/nginx:1.17
    environment:
      - NGINX_ROOT=/var/www/html/m2
      - NGINX_PUBLIC=/pub
      - NGINX_TEMPLATE=magento2.conf
    ports:
      - 80:80

networks:
  default: